language: java

## safelist
#branches:
#  only:
#    - master

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -f pom.xml clean verify -Pdocker

after_success:
  - echo "$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_BRANCH"

  - docker build -t $TRAVIS_REPO_SLUG:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $TRAVIS_REPO_SLUG:latest

notifications:
  email:
    recipients:
      - maria.ic.mihai@gmail.com
    on_success: never # default: change
    on_failure: always # default: always